### ISSUE TITLE
errors when run on raspberry zero

### ISSUE THREAD

**Issue by kekemuyu** [donnie4w/go-logger#24]
runtime/debug.Stack(0x1839dc4, 0x170748, 0x29fea8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x78
github.com/donnie4w/go-logger/logger.catchError()
        /home/pi/go/src/github.com/donnie4w/go-logger/logger/logw.go:417 +0x30
panic(0x170748, 0x29fea8)
        /usr/local/go/src/runtime/panic.go:679 +0x194
runtime/internal/atomic.goXadd64(0x183e8ac, 0x13, 0x0, 0x183e880, 0x13)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
github.com/donnie4w/go-logger/logger.(*fileBean).addsize(...)
        /home/pi/go/src/github.com/donnie4w/go-logger/logger/logw.go:356
github.com/donnie4w/go-logger/logger.(*logBean).log(0x186c000, 0x18fc27, 0x5, 0x1839ee8, 0x2, 0x2)
        /home/pi/go/src/github.com/donnie4w/go-logger/logger/logw.go:257 +0x13c
github.com/donnie4w/go-logger/logger.(*logBean).debug(...)
        /home/pi/go/src/github.com/donnie4w/go-logger/logger/logw.go:274
github.com/donnie4w/go-logger/logger.Debug(...)
        /home/pi/go/src/github.com/donnie4w/go-logger/logger/logger.go:132
main.ConfigRuntime()

**Comment by donnie4w** [comment]
the error arises within the goXadd64 method in the runtime/internal/atomic package, which corresponds to the atomic.AddInt64 function called by the application. This issue suggests potential problems at the lower level and could be due to:
Mismatch between the compilation target and hardware architecture; verify that the GOARCH environment variable in your Go compilation environment is correctly set for the target architecture (for Raspberry Pi Zero, it should be arm or more specifically arm6).
Issues with the operating system or firmware; consider updating the firmware and system of the Raspberry Pi to ensure they are up-to-date.
